export const THEMES = [
  {
    id: 'green',
    name: 'Emerald Green',
    primary: '#10b981',
    secondary: '#ffffff',
    splitTop: '#10b981',
    splitBottom: '#ffffff',
    bgClass: 'bg-emerald-600',
    lightBgClass: 'bg-emerald-50',
    textClass: 'text-emerald-600',
    borderClass: 'border-emerald-200',
    ringClass: 'ring-emerald-500',
    slashGradient: 'from-emerald-500 to-teal-700',
    splitStyle: { background: 'linear-gradient(135deg, #10b981 50%, #ffffff 50%)' },
    appBg: 'bg-white',
    cardBg: 'bg-white',
    cardBorder: 'border-gray-200/80',
    sidebarBg: 'bg-white',
    sidebarBorder: 'border-gray-200',
    sidebarInactive: 'text-gray-600 hover:bg-gray-100 hover:text-gray-900',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-600',
    textMuted: 'text-gray-400',
    divideColor: 'divide-gray-100',
    isDark: false,
  },
  {
    id: 'blue',
    name: 'Ocean Blue',
    primary: '#2563eb',
    secondary: '#e0f2fe',
    splitTop: '#2563eb',
    splitBottom: '#e0f2fe',
    bgClass: 'bg-blue-600',
    lightBgClass: 'bg-blue-50',
    textClass: 'text-blue-600',
    borderClass: 'border-blue-200',
    ringClass: 'ring-blue-500',
    slashGradient: 'from-blue-500 to-indigo-700',
    splitStyle: { background: 'linear-gradient(135deg, #2563eb 50%, #e0f2fe 50%)' },
    appBg: 'bg-[#f0f9ff]',
    cardBg: 'bg-white',
    cardBorder: 'border-sky-200/70',
    sidebarBg: 'bg-[#e0f2fe]/70',
    sidebarBorder: 'border-sky-200/80',
    sidebarInactive: 'text-sky-900/70 hover:bg-sky-200/50 hover:text-sky-950',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    textMuted: 'text-slate-400',
    divideColor: 'divide-sky-100',
    isDark: false,
  },
  {
    id: 'purple',
    name: 'Royal Violet',
    primary: '#7c3aed',
    secondary: '#f3e8ff',
    splitTop: '#7c3aed',
    splitBottom: '#f3e8ff',
    bgClass: 'bg-purple-600',
    lightBgClass: 'bg-purple-50',
    textClass: 'text-purple-600',
    borderClass: 'border-purple-200',
    ringClass: 'ring-purple-500',
    slashGradient: 'from-purple-500 to-fuchsia-700',
    splitStyle: { background: 'linear-gradient(135deg, #7c3aed 50%, #f3e8ff 50%)' },
    appBg: 'bg-[#faf5ff]',
    cardBg: 'bg-white',
    cardBorder: 'border-purple-200/70',
    sidebarBg: 'bg-[#f3e8ff]/70',
    sidebarBorder: 'border-purple-200/80',
    sidebarInactive: 'text-purple-900/70 hover:bg-purple-200/50 hover:text-purple-950',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-600',
    textMuted: 'text-gray-400',
    divideColor: 'divide-purple-100',
    isDark: false,
  },
  {
    id: 'sunset',
    name: 'Sunset Orange',
    primary: '#f97316',
    secondary: '#ffedd5',
    splitTop: '#f97316',
    splitBottom: '#ffedd5',
    bgClass: 'bg-orange-500',
    lightBgClass: 'bg-orange-50',
    textClass: 'text-orange-500',
    borderClass: 'border-orange-200',
    ringClass: 'ring-orange-500',
    slashGradient: 'from-orange-500 to-amber-600',
    splitStyle: { background: 'linear-gradient(135deg, #f97316 50%, #ffedd5 50%)' },
    appBg: 'bg-[#fff7ed]',
    cardBg: 'bg-white',
    cardBorder: 'border-orange-200/70',
    sidebarBg: 'bg-[#ffedd5]/70',
    sidebarBorder: 'border-orange-200/80',
    sidebarInactive: 'text-orange-900/70 hover:bg-orange-200/50 hover:text-orange-950',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-600',
    textMuted: 'text-gray-400',
    divideColor: 'divide-orange-100',
    isDark: false,
  },
  {
    id: 'midnight',
    name: 'Midnight Slate',
    primary: '#0f172a',
    secondary: '#1e293b',
    splitTop: '#334155',
    splitBottom: '#0f172a',
    bgClass: 'bg-slate-900',
    lightBgClass: 'bg-slate-800',
    textClass: 'text-emerald-400',
    borderClass: 'border-slate-800',
    ringClass: 'ring-emerald-500',
    slashGradient: 'from-slate-800 to-zinc-950',
    splitStyle: { background: 'linear-gradient(135deg, #334155 50%, #0f172a 50%)' },
    appBg: 'bg-[#0a0f1d]',
    cardBg: 'bg-[#131b2e]',
    cardBorder: 'border-slate-800/80',
    sidebarBg: 'bg-[#0f172a]',
    sidebarBorder: 'border-slate-800',
    sidebarInactive: 'text-slate-400 hover:bg-slate-800 hover:text-white',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    divideColor: 'divide-slate-800',
    isDark: true,
  },
];

export function getTheme(themeId) {
  if (!themeId) {
    return THEMES.find(t => t.id === 'midnight') || THEMES[0];
  }
  return THEMES.find(t => t.id === themeId) || THEMES.find(t => t.id === 'midnight') || THEMES[0];
}
